### ISSUE TITLE
Suggestion: Change the Typography control styling

### ISSUE THREAD

**Issue by VladNov** [themeum/kirki#1055]
It is not an issue report, but a suggestion to change a bit the styling of the Typography control from box shadow to border 1px solid #ddd.

**Comment by Vishal-Deshpande** [comment]
@VladNov I agree with you. Here is a pull request. https://github.com/aristath/kirki/pull/1057

Lets see what @aristath has to say.

**Comment by aristath** [comment]
I agree that the box-shadow is a bit weird...
The reason it was done this way was to make it visually clear that the controls inside the typography control are grouped and control the same things.
Using a border like the one suggested makes this grouping visually less clear so I'm a bit hesitant to do this.

I'm with you though, this needs improving.
Any more ideas?

**Comment by rahulv3a** [comment]
I add the following CSS to Customizer of my projects to make it visually appealing.

``` CSS
#customize-theme-controls .accordion-section-content {
  background-color: #fff;
}

#customize-theme-controls .accordion-section-content li {
  padding-bottom: 14px;
  border-bottom: 1px solid #f5f5f5;
}

#customize-theme-controls .accordion-section-content li:last-of-type {
  padding-bottom: 0;
  border-bottom: none;
}

#customize-theme-controls .control-section-kirki-expanded {
  border-bottom: 1px solid #ddd;
}
```

This makes the background from gray to white and adds very light borders between fields. This also solves Typography control's box-shadow issue.
