### ISSUE TITLE
Kirki_Fonts_Google::$force_load_all_variants doesn't work anymore

### ISSUE THREAD

**Issue by Micemade** [themeum/kirki#1420]
### Issue description:
Force loading Google Font variants doesn't work after 3+ with code bellow. I used it for body font, so the user can use regular, bold, italic in post editor. I believe that multi-select variant would be really proper solution.

### Version used:
3.0.4

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
add_action( 'wp', function() {
	if ( class_exists( 'Kirki_Fonts_Google' ) ) {
		Kirki_Fonts_Google::$force_load_all_variants = true;
	}
});
```

**Comment by Micemade** [comment]
Please, advise ...
thnx

**Comment by vlthemes** [comment]
```
function osmos_font_add_all_variants() {
    if (class_exists('Kirki_Fonts_Google')) {
        Kirki_Fonts_Google::$force_load_all_variants = true;
        Kirki_Fonts_Google::$force_load_all_subsets = true;
    }
}

add_action('after_setup_theme', 'osmos_font_add_all_variants');
```

**Comment by Micemade** [comment]
Yes, that works ! Thank you very much @vlthemes  ! Although I have tried with "after_setup_theme", but I didn't include `Kirki_Fonts_Google::$force_load_all_subsets = true` ... Thought it wasn't necessary, because I just wanted all variants, not subsets ...
Anyhow, big thanks !

**Comment by Micemade** [comment]
@vlthemes ... ehm ... no. It seems that it doesn't work, after all. It was a premature celebration ... :(
Any ideas what to try ... ?

**Comment by aristath** [comment]
That last commit should fix the issue, can you please verify it by testing the develop branch from this repository?

**Comment by Micemade** [comment]
Sorry, I wasn't able to reply sooner - I was away from computer. It seems it works ( I see you already included fix in wp.org update ).
Thank you very much.

**Comment by aristath** [comment]
Thanks for checking! 👍

**Comment by notrealdev** [comment]
Hi
```php
function osmos_font_add_all_variants() {
    if (class_exists('Kirki_Fonts_Google')) {
        Kirki_Fonts_Google::$force_load_all_variants = true;
        Kirki_Fonts_Google::$force_load_all_subsets = true;
    }
}

add_action('after_setup_theme', 'osmos_font_add_all_variants');
```
not working for me

ouput:
```css
/* devanagari */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  src: local('Poppins Regular'), local('Poppins-Regular'), url(https://fonts.gstatic.com/s/poppins/v4/gG8m82oGcrBJF727xHU04fY6323mHUZFJMgTvxaG2iE.woff2) format('woff2');
  unicode-range: U+02BC, U+0900-097F, U+1CD0-1CF6, U+1CF8-1CF9, U+200B-200D, U+20A8, U+20B9, U+25CC, U+A830-A839, U+A8E0-A8FB;
}
/* latin-ext */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  src: local('Poppins Regular'), local('Poppins-Regular'), url(https://fonts.gstatic.com/s/poppins/v4/F4YWuALHubF63LLQPw0rMfY6323mHUZFJMgTvxaG2iE.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  src: local('Poppins Regular'), local('Poppins-Regular'), url(https://fonts.gstatic.com/s/poppins/v4/HLBysyo0MQBO_7E-DWLwzg.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
}
```

not font-weight: 300, 600 or 700
// Version 3.0.9 stable
