### ISSUE TITLE
Odd color interpolation in repo version

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#172]
Hi Aristeides,

As I said on twitter im switching my projects to the repo version for stability's sake.
I've first move my projects locally but im seeing odd behaviour in color interpolation, but just for some colors, quick example:

https://cloudup.com/ctqKnO3WbtJ

Here's what you need to consider in this screenshot:

The var dump shows the following variable:

``` php
'header_bg_color' => string '#043a59' (length=7)
```

This var is setup in Kirki like this:

``` php
    $controls[] = array(
        'type' => 'color',
        'section' => 'colors_section_header',
        'settings' => 'header_bg_color',
        'default' => '#ffffff',
        'label'    => __( 'Header Background', 'wip' ),
        'output' => array(
            array(
                'element'  => '.site-header',
                'property' => 'background-color'
            ),
        ),
    );
```

But, if you see the Styles inspector at the right, you'll see that the color that is actually being outputted into CSS is `#F43a59`, a bright pink instead of the choose navy blue.\

I've tried changing and saving the options again but no luck.

Anything I can do about this?

**Comment by lmartins** [comment]
Another example:
![screen shot 2015-04-06 at 11 21 57](https://cloud.githubusercontent.com/assets/151981/7003256/2d1b2b2a-dc4f-11e4-93fc-b265202e58e4.png)

The greenish you see in the header should actually be the blue visible on the customiser for the input "Header Background", and the inputs on header, showing in pink, should actually be shades of the background color:

``` css
.minicart,
        input[type=search]{
            background-color: <?php echo Kirki_Color::get_brightness($header_bg) < 120 ? Kirki_Color::adjust_brightness($header_bg, 20) : Kirki_Color::adjust_brightness($header_bg, -20) ?>;
        }
```
