### ISSUE TITLE
Section Heading

### ISSUE THREAD

**Issue by JakeHenshall** [themeum/kirki#1838]
Hi,

Is there any way to separate sections like the attached image.

<img width="299" alt="screen shot 2018-03-20 at 00 44 30" src="https://user-images.githubusercontent.com/4720782/37629680-0dec24b2-2bd8-11e8-9bae-3b5681a735e3.png">

Would I need to create a Custom Function to allow me to do this?

Thanks, Jake,

**Comment by anthonyryanrusso** [comment]
You could just use the custom control.  http://aristath.github.io/kirki/docs/controls/custom.html

**Comment by vlthemes** [comment]
```php
Kirki::add_field( 'config', array(
	'type' => 'custom',
	'settings' => 'heading' . $priority++,
	'section' => 'section_header_general',
	'default' => '<div class="kirki-separator">'.esc_html__( 'Example', 'domain' ).'</div>',
	'priority' => $priority++,
) );
```
Admin CSS:
```css
.kirki-separator {
	margin: 0 -12px;
	padding: 10px 12px;
	color: #555d66;
	text-align: center;
	text-transform: uppercase;
	letter-spacing: 2px;
	font-weight: 700;
	border-top: 1px solid #ddd;
	border-bottom: 1px solid #ddd;
	background-color: #fff;
}
```
