### ISSUE TITLE
How to use background-gradients?

### ISSUE THREAD

**Issue by endcoreCL** [themeum/kirki#268]
Hey,

your Plugin is very nice, thanks!

How can i use a color-field for background-gradients (with output!)? The css must look as follows.

``` css
#header {
    background: #fff;
    background: -moz-linear-gradient(top,  #fff 0%, #fafafa 100%);
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fff), color-stop(100%,#fafafa));
    background: -webkit-linear-gradient(top,  #fff 0%,#fafafa 100%);
    background: -o-linear-gradient(top,  #fff 0%,#fafafa 100%);
    background: -ms-linear-gradient(top,  #fff 0%,#fafafa 100%);
    background: linear-gradient(to bottom,  #fff 0%,#fafafa 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fff', endColorstr='#fafafa',GradientType=0 );
}
```
