### ISSUE TITLE
Select2 fields: add a placeholder option

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#285]
Just a little sugestion for improvement :smiley: 

Right now, the Select2 Mutliple field have the exact appearance of the text fields, but very different functions.

Would be interesting to add a placeholder option to improve the usability of the field a bit, like this:

![select2-multiple-placeholder](https://cloud.githubusercontent.com/assets/1451087/8890011/42301eda-32c6-11e5-84c1-b1e36e5c07bd.gif)

We could add the text in the description, but a placeholder is more direct. In a panel full of complex options, it could be useful.

In Select2 Multiple field, this could be easily achieved like this:

``` php
// Line 50 in controls/select2-multiple/class-kirki-controls-select2-multiple-control.php
// Adding a `data-placeholder` attribute to the select element
<select data-customize-setting-link="<?php echo esc_attr( $id ); ?>" data-placeholder="Placeholder text" class="select2" multiple="multiple">


// Line 57 in controls/select2-multiple/class-kirki-controls-select2-multiple-control.php
// Changing the Select2 jQuery
jQuery(document).ready(function($) {
    $('.select2').select2({
        minimumResultsForSearch: -1,
        placeholder: function() {
            $(this).data('placeholder');
        }
    });
});
```

But in this example, the placeholder text would be hardcoded. Maybe adding an extra `placeholder` argument in configs would do.

**Comment by pagelab** [comment]
Another simpler option is just to add a little icon at the right of the field, like this:

``` css
.select2-container--default {
  position: relative;
}
.select2-container--default .select2-selection--multiple:before {
  content: "\f179";
  font-family: dashicons;
  display: block;
  position: absolute;
  right: 5px;
  top: 10px;
  cursor: pointer;
  font-size: 20px;
  color: #ACA99F;
}
```

![select-multiple-icon](https://cloud.githubusercontent.com/assets/1451087/8891552/3a576328-3305-11e5-9942-7a3b13016821.png)
