### ISSUE TITLE
Some Google fonts don't work due to a faulty CSS

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#600]
When Kirki generates CSS for Google Fonts, it doesn't add quotes around the name of Google font. It causes some fonts (like Exo 2) to not to work. Plus, it is not a valid W3C CSS.

> If a font name contains white-space, it must be quoted.
> 
> To avoid mistakes in escaping, it is recommended to quote font family names that contain white space, digits, or punctuation characters other than hyphens.
> 
> – [www.w3.org](https://www.w3.org/TR/CSS2/fonts.html)

CSS that is currently generated:

``` CSS
.class {
  font-family: Exo 2, Helvetica, Arial, sans-serif;
}
```

CSS that should be generated

``` CSS
.class {
  font-family: "Exo 2", Helvetica, Arial, sans-serif;
}
```
