### ISSUE TITLE
Typography control does not apply changes after save [$100]

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#717]
**Issue: Typography control stops responding after its changes have been saved**

How to replicate:

Install the develop branch of the plugin in a WordPress installation & activate the plugin.
Go to your theme's `functions.php` file and add the following:

``` php
Kirki::add_section( 'kirki_typography_test', array(
    'title'      => esc_attr__( 'Typography Test', 'test' ),
    'priority'   => 1,
    'capability' => 'edit_theme_options',
) );

Kirki::add_field( 'global', array(
    'type'        => 'typography',
    'settings'    => 'typography_test',
    'label'       => esc_attr__( 'Typography Control', 'test' ),
    'description' => esc_attr__( 'This is a composite typography control. It saves the data as an array, and you can define which of the controls you want shown.', 'test' ),
    'tooltip'     => esc_attr__( 'This is a tooltip', 'test' ),
    'section'     => 'kirki_typography_test',
    'priority'    => 10,
    'output'      => array(
        array( 'element' => 'body, body p' ),
    ),
    'default'     => array(
        'font-family'    => 'Roboto',
        'variant'        => 'regular',
        'font-size'      => '1.1em',
        'line-height'    => '1.5',
        'letter-spacing' => '0',
        'color'          => '#333333',
    ),
) );
```

Then go to the customizer, make a change to the font-family for example, and you should see the font-family of the body change to what you have defined.
Next, save your changes.
Once you've saved your options, try changinf the font-family again.
You'll see that the preview refreshes but the changes made to the control are not getting applied.
the value is properly detected via the control's JS (using `control.setting.set( value );`, if you do a `console.log( value );` you'll see it's fine there), but for some reason it's just not getting detected by the customizer.
Please note that other controls work fine, this appears to be a glitch specific to this control.
##

**Comment by misfist** [comment]
I finding the following when using the _S fork with Kirki Toolkit Version 2.2.3:

Typography Controls:

* `letter-spacing:;` is output even though there is no letter spacing field supplied.
* `color` is not output at all even when a color is selected.

Here is a screenshot of my saved selection:

![bildschirmfoto 2016-03-19 um 4 47 45 nachm](https://cloud.githubusercontent.com/assets/709248/13901212/976202be-edf2-11e5-806a-972faa5f4063.png)

Here is the CSS that is output:

```css
body{font-family:Lato, Helvetica, Arial, sans-serif;font-weight:300;font-size:16px;line-height:1.5;letter-spacing:;}.h1,.h2,.h3,.h4,.h5,.h6,h1,h2,h3,h4,h5,h6{font-family:Roboto, Helvetica, Arial, sans-serif;font-weight:100;font-size:;line-height:;letter-spacing:;}Arial, sans-serif;font-weight:100;font-size:;line-height:;letter-spacing:;}
```
