### ISSUE TITLE
New Control Request: Separator Control

### ISSUE THREAD

**Issue by Vishal-Deshpande** [themeum/kirki#803]
I would like to request new control "separator".

Customizer lacks space and some times you need <hr> hr line to visually separate controls. I searched in docs but could not find anything similar.

Can we have separator control to better manage the messy customizer. Color, thickness choices would be handy. 

Redux has something similar to this https://docs.reduxframework.com/core/fields/divide/

**Comment by ghost** [comment]
Oh yes please. Great request on this.

**Comment by aristath** [comment]
Actually we used to have a "separator" control back in version 0.8 if I remember correctly.
Then we introduced the "custom" control and a separator was no longer needed.

You can add one like this:

``` php
Kirki::add_field( 'my_config', array(
    'type'        => 'custom',
    'settings'    => uniqid( 'separator' ),
    'section'     => 'my_section',
    'default'     => '<hr>',
    'priority'    => 23,
) );
```

You can change the `<hr>` to something like `<div style="padding: 5px; border-top: 1px red; border-bottom: 5px blue;"></div>` or just do whatever you want with it!
I've seen most people use it as a contextual separator using a div properly styled with a title included. :+1:

**Comment by rahulv3a** [comment]
Just sharing my way of doing the same:

``` php
Kirki::add_field( 'my_config', array(
    'type'        => 'custom',
    'settings'    => uniqid( 'separator' ),
    'section'     => 'my_section',
    'default'     => '<div class="customizer-separator"></div>',
    'priority'    => 23,
) );
```

Then load a CSS file in the customizer.

``` php
function my_customizer_controls_styles() {
  $current_theme_version = wp_get_theme()->get( 'Version' );
  wp_enqueue_style( 'customizer', get_template_directory_uri() . '/inc/customizer/css/main.css', array(), $current_theme_version );
}
add_action('customize_controls_enqueue_scripts', 'my_customizer_controls_styles');
```

Then add custom cutomizer CSS in `main.css`. Using a css class instead of incline css helps if we decide to tweak styles for the separator later on.

``` CSS
.customizer-separator {
  /*  styles for separator goes here */
}
```

I usually add the following styles to `main.css` in order to make it visually more appealing.

``` CSS
#customize-theme-controls .accordion-section-content {
  background-color: #fff;
}

#customize-theme-controls .accordion-section-content li {
  padding-bottom: 14px;
  border-bottom: 1px solid #f5f5f5;
}

#customize-theme-controls .accordion-section-content li:last-of-type,
#customize-theme-controls .accordion-section-content li.customize-section-description-container {
  padding-bottom: 0;
  border-bottom: none;
}
```
