### ISSUE TITLE
Styling the Customizer (minor issue with width)

### ISSUE THREAD

**Issue by Rayken** [themeum/kirki#969]
### Issue description:

When using the 'kirki/config' filter to alter the customizer one cannot change the _width_ without supplying 'color_accent' which I believe to be a bug. What does the width have to do with changing the color? I don't want to change colors I want to change the width!

So for some reason, without specifying `'color_accent'`, `'width'` is being ignored. A quick workaround for this is simply to supply the default color, which I think is #008ec2.

EDIT: There needs to be another rule applied as well to allow for the 'collapse' to work with the custom 'width':

``` css
.wp-full-overlay.collapsed .wp-full-overlay-sidebar {
    overflow: visible; /* already there */
    margin-left: -30vw; /* whatever your width setting is.. */
}
```
### Version used:

Develop branch
### Code to reproduce the issue (config + field(s))

https://kirki.org/docs/advanced/styling-the-customizer.html
